name: bad_code_detector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  wwwqr_sec_check_job:
    runs-on: ubuntu-latest
    name: Hunting
    steps:
      - uses: actions/checkout@v4
      - name: Installing external software
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build and run tests
        run: |
          #Google test setup
          cd /usr/src/googletest/googletest
          sudo cmake .
          sudo make
          #
          cd $GITHUB_WORKSPACE/fancy-water-tests
          g++ -x c++-header pch.h -o pch.h.gch
          g++ -c pch.h
          g++ -c test_main.cpp -o test_main.o
          g++ -c tests/your_test_file.cpp -o test_file.o
          g++ test_main.o test_file.o pch.o -lgtest -lgtest_main -pthread -o test_exec
          chmod 0777 test_exec
          ./test_exec
