name: bad_code_detector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  wwwqr_sec_check_job:
    runs-on: ubuntu-latest
    name: Hunting
    steps:
      - uses: actions/checkout@v4
      - name: ls test
        run: ls

      - name: Build and run executable
        run: |
          cd fancy-water-tests/github
          g++ main.cpp
          chmod 0777 out.a
          mv out.a exec
          ./exec
