name: bad_code_detector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  wwwqr_sec_check_job:
    runs-on: ubuntu-latest
    name: Hunting
    steps:
      - uses: actions/checkout@v4
      - name: Installing external software
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build and run tests
        run: |
          cd fancy-water-tests
          mkdir test_build
          cd test_build
          cmake ..
          cmake --build .
          ctest --output-on-failure

